apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-ingress-class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /cd/$2
spec:
 ingressClassName: nginx
 tls:
 - hosts: 
   - {cicdWebhook}
   secretName: webhook-tls
 rules:
  - host: {cicdWebhook}
    http:
      paths:
      - path: /cd(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: el-conexp-listener
            port: 
              number: 8080
